-- ============================================================
-- V1 · 文件元数据表（file-service · 磁盘存储，DB 仅元数据）
--
-- 设计依据：ADR-0021（Flyway）+ ADR-0025（独立迁移链 + 强制租户）
-- 存储：本地磁盘 {storeDir}/{tenant_id}/{stored_name}；stored_name 为 UUID 防路径注入
-- ============================================================

CREATE TABLE files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(64)  NOT NULL,
    content_type  VARCHAR(128),
    size          BIGINT       NOT NULL,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_files_tenant_id ON files (tenant_id);

COMMENT ON TABLE files IS '文件元数据（file-service · 磁盘存储 /data/files · tenant_id 行级隔离 · ADR-0025）';
COMMENT ON COLUMN files.tenant_id IS '归属租户（逻辑引用 user-service tenants.id，无 DB FK）';
COMMENT ON COLUMN files.original_name IS '原始文件名（用户上传）';
COMMENT ON COLUMN files.stored_name IS '磁盘文件名（UUID，防路径注入）';
COMMENT ON COLUMN files.content_type IS 'MIME 类型';
COMMENT ON COLUMN files.size IS '文件大小（字节）';
COMMENT ON COLUMN files.is_deleted IS '软删标记（回收站语义：软删后不可下载）';
