-- ============================================================
-- V10 · 权限点体系（permissions + role_permissions · ADR-0024 Phase 2）
--
-- 平台基础层横切能力：菜单可见性 + 接口鉴权共用同一权限码数据源。
--   permissions      权限点定义（code 唯一，PLATFORM/TENANT 两级 scope）
--   role_permissions 角色-权限多对多（PK(role_id, permission_id)）
-- 初始矩阵（与 ADR-0024 权限矩阵 + 前端 access.ts 对齐）：
--   PLATFORM_ADMIN 全量；TENANT_ADMIN 租户管理+业务；USER 租户内业务；DUTY_OFFICER 仅 iot:monitor
-- 说明：DUTY_OFFICER 角色当前未 seed（前端预留），其映射行在角色创建后由后续迁移/管理端补齐；
--       本迁移用条件 JOIN，角色不存在时自然跳过，幂等安全。
-- ============================================================

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    scope       VARCHAR(12)  NOT NULL,
    description VARCHAR(500),
    is_system   BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_permissions_code UNIQUE (code),
    CONSTRAINT ck_permissions_scope CHECK (scope IN ('PLATFORM', 'TENANT'))
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX idx_permissions_scope ON permissions (scope);
CREATE INDEX idx_role_permissions_permission ON role_permissions (permission_id);

COMMENT ON TABLE permissions IS '权限点（RBAC · ADR-0024 Phase 2）：菜单可见性与接口鉴权共用数据源';
COMMENT ON COLUMN permissions.code IS '权限码：<域>:<资源>:<动作>（如 legal:use / tenant:manage）';
COMMENT ON COLUMN permissions.scope IS '范围：PLATFORM（平台运营）/ TENANT（租户内）';
COMMENT ON COLUMN permissions.is_system IS '系统内置权限点（只读）';
COMMENT ON TABLE role_permissions IS '角色-权限关联（多对多）';

-- 权限点 seed（平台基础层内置）
INSERT INTO permissions (code, name, scope, description, is_system) VALUES
  ('tenant:manage',   '租户管理',     'PLATFORM', '平台级：租户/角色/审计',             true),
  ('user:manage',     '用户管理',     'TENANT',   '租户级：管理本租户用户与邀请',        true),
  ('user:list',       '用户查看',     'TENANT',   '租户内用户列表',                      true),
  ('crm:use',         'CRM 使用',     'TENANT',   '客户与线索',                          true),
  ('inventory:use',   '进销存使用',   'TENANT',   '商品与出入库',                        true),
  ('finance:use',     '财务使用',     'TENANT',   '记账本',                              true),
  ('approval:use',    '审批使用',     'TENANT',   '审批流',                              true),
  ('legal:use',       '法律域使用',   'TENANT',   '案件/律时/卷宗/闸门（ADR-0036）',      true),
  ('iot:monitor',     '监控只读',     'TENANT',   '驾驶舱/总览/拓扑/告警（值班员可见）',  true),
  ('iot:config',      '监控配置',     'TENANT',   '设备/产品物模型/规则',                true);

-- 角色-权限矩阵（条件 JOIN：角色不存在时该行自然跳过，幂等）
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE (r.code = 'PLATFORM_ADMIN'
       AND p.code IN ('tenant:manage','user:manage','user:list','crm:use','inventory:use',
                      'finance:use','approval:use','legal:use','iot:monitor','iot:config'))
   OR (r.code = 'TENANT_ADMIN'
       AND p.code IN ('user:manage','user:list','crm:use','inventory:use','finance:use',
                      'approval:use','legal:use','iot:monitor','iot:config'))
   OR (r.code = 'USER'
       AND p.code IN ('user:list','crm:use','inventory:use','finance:use','approval:use',
                      'legal:use','iot:monitor'))
   OR (r.code = 'DUTY_OFFICER'
       AND p.code IN ('iot:monitor'));
