-- ============================================================
-- V10__add_tenant_grants.sql · 统一账号跨公司授权（集团管理行业版 · group）
--
-- 集团版需求（docs/group-edition-design.md §3.2 统一账号权限）：
--   总部用户主属集团租户，可被授权访问多个子公司租户。
--   user_tenant_grants = 用户 × 子公司租户 × 角色（子公司维度授权）。
--   主属租户无需授权（users.tenant_id 天然可访问）。
-- ============================================================

CREATE TABLE user_tenant_grants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tenant_id   BIGINT      NOT NULL REFERENCES tenants (id),
    role_id     BIGINT      NOT NULL REFERENCES roles (id),
    granted_by  BIGINT      REFERENCES users (id),
    granted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_user_tenant_grants UNIQUE (user_id, tenant_id, role_id)
);

COMMENT ON TABLE user_tenant_grants IS '统一账号跨子公司授权（集团版 · 用户×子公司租户×角色）';
COMMENT ON COLUMN user_tenant_grants.granted_by IS '授权人（总部管理员）';
COMMENT ON COLUMN user_tenant_grants.granted_at IS '授权时间';

CREATE INDEX idx_tenant_grants_user   ON user_tenant_grants (user_id);
CREATE INDEX idx_tenant_grants_tenant ON user_tenant_grants (tenant_id);
